/**
 * SEC filer number for each listed stock, generated by scripts/fetch-ciks.mjs.
 *
 * EDGAR indexes everything by CIK, so this is the first step of any insider
 * lookup. Do not edit by hand - re-run the script, which reads the tickers back
 * out of the registry so the two cannot drift.
 *
 * A ticker absent from here has no Form 4 filings to fetch: an ETF, or a
 * foreign issuer that reports on 6-K instead. Absence is an answer, not a gap.
 */
export type Filer = { cik: string; issuer: string };

export const FILERS: Record<string, Filer> = {
  HIMS: { cik: "0001773751", issuer: "Hims & Hers Health, Inc." },
  RDDT: { cik: "0001713445", issuer: "Reddit, Inc." },
  NVDA: { cik: "0001045810", issuer: "NVIDIA CORP" },
  CRCL: { cik: "0001876042", issuer: "Circle Internet Group, Inc." },
  META: { cik: "0001326801", issuer: "Meta Platforms, Inc." },
  SPCX: { cik: "0001181412", issuer: "SPACE EXPLORATION TECHNOLOGIES CORP" },
  TSLA: { cik: "0001318605", issuer: "Tesla, Inc." },
  GOOGL: { cik: "0001652044", issuer: "Alphabet Inc." },
  MSTR: { cik: "0001050446", issuer: "Strategy Inc" },
  AMC: { cik: "0001411579", issuer: "AMC ENTERTAINMENT HOLDINGS, INC." },
  COIN: { cik: "0001679788", issuer: "Coinbase Global, Inc." },
  RBLX: { cik: "0001315098", issuer: "Roblox Corp" },
  AAPL: { cik: "0000320193", issuer: "Apple Inc." },
  DJT: { cik: "0001849635", issuer: "Trump Media & Technology Group Corp." },
  LLY: { cik: "0000059478", issuer: "ELI LILLY & Co" },
  MU: { cik: "0000723125", issuer: "MICRON TECHNOLOGY INC" },
  GME: { cik: "0001326380", issuer: "GameStop Corp." },
  TSM: { cik: "0001046179", issuer: "TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD" },
  BB: { cik: "0001070235", issuer: "BLACKBERRY Ltd" },
  SNAP: { cik: "0001564408", issuer: "Snap Inc" },
  PLTR: { cik: "0001321655", issuer: "Palantir Technologies Inc." },
  SNDK: { cik: "0002023554", issuer: "Sandisk Corp" },
  COST: { cik: "0000909832", issuer: "COSTCO WHOLESALE CORP /NEW" },
  MRVL: { cik: "0001835632", issuer: "Marvell Technology, Inc." },
  QUBT: { cik: "0001758009", issuer: "Quantum Computing Inc." },
  INTC: { cik: "0000050863", issuer: "INTEL CORP" },
  MRNA: { cik: "0001682852", issuer: "Moderna, Inc." },
  DELL: { cik: "0001571996", issuer: "Dell Technologies Inc." },
  AMD: { cik: "0000002488", issuer: "ADVANCED MICRO DEVICES INC" },
  TTWO: { cik: "0000946581", issuer: "TAKE TWO INTERACTIVE SOFTWARE INC" },
  BULL: { cik: "0001866364", issuer: "Webull Corp" },
  JNJ: { cik: "0000200406", issuer: "JOHNSON & JOHNSON" },
  IBM: { cik: "0000051143", issuer: "INTERNATIONAL BUSINESS MACHINES CORP" },
  BE: { cik: "0001664703", issuer: "Bloom Energy Corp" },
  F: { cik: "0000037996", issuer: "FORD MOTOR CO" },
  AMZN: { cik: "0001018724", issuer: "AMAZON COM INC" },
  MSFT: { cik: "0000789019", issuer: "MICROSOFT CORP" },
  PFE: { cik: "0000078003", issuer: "PFIZER INC" },
  GLXY: { cik: "0001859392", issuer: "Galaxy Digital Inc." },
  NU: { cik: "0001691493", issuer: "Nu Holdings Ltd." },
  FIG: { cik: "0001579878", issuer: "Figma, Inc." },
  LULU: { cik: "0001397187", issuer: "lululemon athletica inc." },
  NFLX: { cik: "0001065280", issuer: "NETFLIX INC" },
  BABA: { cik: "0001577552", issuer: "Alibaba Group Holding Ltd" },
  RIVN: { cik: "0001874178", issuer: "Rivian Automotive, Inc. / DE" },
  USAR: { cik: "0001970622", issuer: "USA Rare Earth, Inc." },
  BA: { cik: "0000012927", issuer: "BOEING CO" },
  ON: { cik: "0001097864", issuer: "ON SEMICONDUCTOR CORP" },
  WYFI: { cik: "0002042022", issuer: "WhiteFiber, Inc." },
  UPS: { cik: "0001090727", issuer: "UNITED PARCEL SERVICE INC" },
  CCL: { cik: "0000815097", issuer: "Carnival Corp Ltd." },
  POET: { cik: "0001437424", issuer: "POET TECHNOLOGIES INC." },
  RCAT: { cik: "0000748268", issuer: "Red Cat Holdings, Inc." },
  SHOP: { cik: "0001594805", issuer: "SHOPIFY INC." },
  AVGO: { cik: "0001730168", issuer: "Broadcom Inc." },
  SNOW: { cik: "0001640147", issuer: "Snowflake Inc." },
  CEG: { cik: "0001868275", issuer: "Constellation Energy Corp" },
  ASML: { cik: "0000937966", issuer: "ASML HOLDING NV" },
  HPE: { cik: "0001645590", issuer: "Hewlett Packard Enterprise Co" },
  PENG: { cik: "0001616533", issuer: "Penguin Solutions, Inc." },
  NET: { cik: "0001477333", issuer: "Cloudflare, Inc." },
  DDOG: { cik: "0001561550", issuer: "Datadog, Inc." },
  LMT: { cik: "0000936468", issuer: "LOCKHEED MARTIN CORP" },
  WULF: { cik: "0001083301", issuer: "TERAWULF INC." },
  RUN: { cik: "0001469367", issuer: "Sunrun Inc." },
  FLY: { cik: "0001860160", issuer: "Firefly Aerospace Inc." },
  CLOV: { cik: "0001801170", issuer: "CLOVER HEALTH INVESTMENTS, CORP. /DE" },
  PATH: { cik: "0001734722", issuer: "UiPath, Inc." },
  SOFI: { cik: "0001818874", issuer: "SoFi Technologies, Inc." },
  UMC: { cik: "0001033767", issuer: "UNITED MICROELECTRONICS CORP" },
  IONQ: { cik: "0001824920", issuer: "IonQ, Inc." },
  RKLB: { cik: "0001819994", issuer: "Rocket Lab Corp" },
  AAOI: { cik: "0001158114", issuer: "APPLIED OPTOELECTRONICS, INC." },
  FTNT: { cik: "0001262039", issuer: "Fortinet, Inc." },
  XOM: { cik: "0002115436", issuer: "ExxonMobil Holdings Corp" },
  NOW: { cik: "0001373715", issuer: "ServiceNow, Inc." },
  ANET: { cik: "0001596532", issuer: "Arista Networks, Inc." },
  HWM: { cik: "0000004281", issuer: "Howmet Aerospace Inc." },
  ADBE: { cik: "0000796343", issuer: "ADOBE INC." },
  VRT: { cik: "0001674101", issuer: "Vertiv Holdings Co" },
  CLS: { cik: "0001030894", issuer: "CELESTICA INC" },
  AMAT: { cik: "0000006951", issuer: "APPLIED MATERIALS INC /DE" },
  PWR: { cik: "0001050915", issuer: "QUANTA SERVICES, INC." },
  MPWR: { cik: "0001280452", issuer: "MONOLITHIC POWER SYSTEMS, INC." },
  FIX: { cik: "0001035983", issuer: "COMFORT SYSTEMS USA INC" },
};

/** Reverse lookup, for turning a filing's CIK back into a ticker we list. */
export const TICKER_BY_CIK: Record<string, string> = Object.fromEntries(
  Object.entries(FILERS).map(([ticker, f]) => [f.cik, ticker]),
);

/** CIKs carry leading zeros in EDGAR paths but not in its archive URLs. */
export const bareCik = (cik: string) => String(Number(cik));
