/**
 * Maps each listed stock to its SEC filer number.
 *
 * Insider dealings come from Form 4, and EDGAR indexes filings by CIK rather
 * than by ticker, so every insider lookup needs this translation first. The
 * mapping is effectively static - a company's CIK never changes, and a ticker
 * only moves on a rename or a merger - so it is generated once into a file the
 * application imports rather than fetched at runtime.
 *
 *   node scripts/fetch-ciks.mjs            # report matches and misses
 *   node scripts/fetch-ciks.mjs --write    # rewrite src/lib/ciks.ts
 *
 * ETFs are skipped deliberately. A fund has no officers or directors, so there
 * is no Form 4 to find and a missing entry is the correct answer rather than a
 * gap.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIR = path.dirname(fileURLToPath(import.meta.url));

/**
 * The SEC rejects an anonymous request. Its fair-access policy asks for a
 * contact address in the User-Agent so it can reach whoever is responsible for
 * the traffic, and returns 403 without one.
 */
const UA = {
  "User-Agent": "DIVS Protocol valeinfralabs@gmail.com",
  "Accept-Encoding": "gzip, deflate",
};

/** Reads the tickers out of the registry without importing TypeScript. */
function listedStocks() {
  const src = fs.readFileSync(path.join(DIR, "..", "src", "lib", "exchange.ts"), "utf8");
  const out = [];
  for (const line of src.split("\n")) {
    const m = line.match(/\{ ticker: "([^"]+)", name: "([^"]+)", kind: "(stock|etf)"/);
    if (m && m[3] === "stock") out.push({ ticker: m[1], name: m[2] });
  }
  return out;
}

const stocks = listedStocks();
console.log(`${stocks.length} listed stocks\n`);

const res = await fetch("https://www.sec.gov/files/company_tickers.json", { headers: UA });
if (!res.ok) throw new Error(`SEC ticker file: ${res.status}`);
const table = Object.values(await res.json());

const byTicker = new Map();
for (const row of table) byTicker.set(row.ticker.toUpperCase(), row);

const matched = [];
const missing = [];

for (const s of stocks) {
  const row = byTicker.get(s.ticker.toUpperCase());
  if (!row) {
    missing.push(s);
    continue;
  }
  // CIKs are written as ten digits with leading zeros in EDGAR paths.
  matched.push({
    ticker: s.ticker,
    cik: String(row.cik_str).padStart(10, "0"),
    issuer: row.title,
  });
}

for (const m of matched) console.log(`${m.ticker.padEnd(6)} ${m.cik}  ${m.issuer}`);

if (missing.length) {
  console.log(`\nno SEC filer found: ${missing.map((m) => m.ticker).join(" ")}`);
  console.log("A foreign issuer files 6-K rather than Form 4, so this can be correct.");
}
console.log(`\nmatched ${matched.length} of ${stocks.length}`);

if (!process.argv.includes("--write")) {
  console.log("\nRe-run with --write to update src/lib/ciks.ts");
  process.exit(0);
}

const rows = matched
  .map((m) => `  ${m.ticker}: { cik: "${m.cik}", issuer: ${JSON.stringify(m.issuer)} },`)
  .join("\n");

const file = `/**
 * SEC filer number for each listed stock, generated by scripts/fetch-ciks.mjs.
 *
 * EDGAR indexes everything by CIK, so this is the first step of any insider
 * lookup. Do not edit by hand - re-run the script, which reads the tickers back
 * out of the registry so the two cannot drift.
 *
 * A ticker absent from here has no Form 4 filings to fetch: an ETF, or a
 * foreign issuer that reports on 6-K instead. Absence is an answer, not a gap.
 */
export type Filer = { cik: string; issuer: string };

export const FILERS: Record<string, Filer> = {
${rows}
};

/** Reverse lookup, for turning a filing's CIK back into a ticker we list. */
export const TICKER_BY_CIK: Record<string, string> = Object.fromEntries(
  Object.entries(FILERS).map(([ticker, f]) => [f.cik, ticker]),
);

/** CIKs carry leading zeros in EDGAR paths but not in its archive URLs. */
export const bareCik = (cik: string) => String(Number(cik));
`;

fs.writeFileSync(path.join(DIR, "..", "src", "lib", "ciks.ts"), file);
console.log(`\nwrote ${matched.length} filers to src/lib/ciks.ts`);
